/*
 * generated by Xtext
 */
package org.xtext.example.mydsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CSSeminarsStandaloneSetup extends CSSeminarsStandaloneSetupGenerated{

	public static void doSetup() {
		new CSSeminarsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

