/*
 * generated by Xtext
 */
package org.xtext.example.mydsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CSSeminarsUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.example.mydsl.ui.internal.CSSeminarsActivator.getInstance().getInjector("org.xtext.example.mydsl.CSSeminars");
	}
	
}
